name: Orange22
favicon: null
layout_spectrum: 0.5119148234371096
typography_spectrum: 0.052312458865344524
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9509110467042774
  lightness: 0.7594192810356617
  saturation: 0.049441856099292636
  rhythmicContrast: 0.6010301727801561
purpose: []
